name: "tests"

on: 
    push:
        branches:
          - main
          - dev
    pull_request:
        branches:
          - main

jobs:
  tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        !apt install glpk-utils
        !pip install glpk

    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3